export const CHANGE_DJ_BANNER = "dj/CHANGE_DJ_BANNER";
export const CHANGE_DJ_CATELIST = "dj/DJ_CATELIST";
export const CHANGE_RECOMMEND_LIST_ERROR = "dj/RECOMMEND_LIST_ERROR";
export const CHANGE_ENTER_LOADING = "dj/CHANGE_ENTER_LOADING";
export const CHANGE_ALL_CLASS_INFO = "dj/ALL_CLASS_INFO";
